// directives/proxies.ts (the actual DoodleCanvas component class) and directives/index.ts (just
// a DIRECTIVES bulk-array convenience, not a re-export of the class itself) are generated by
// doodle-ui's own Stencil build - see packages/doodle-ui/stencil.config.ts's angularOutputTarget.
// Not hand-written, don't edit either.
export * from './directives/proxies';
export * from './directives';
export type { StrokeSnapshot } from '@innotopic/doodle-ui';
