allowBuilds:
  '@firebase/util': true
  '@fortawesome/fontawesome-common-types': true
  '@fortawesome/fontawesome-svg-core': true
  '@fortawesome/free-solid-svg-icons': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  re2: true
