/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StrokeSnapshot } from "./components/doodle-canvas/doodle-canvas";
export { StrokeSnapshot } from "./components/doodle-canvas/doodle-canvas";
export namespace Components {
    /**
     * Freehand doodling overlay for an SVG or bitmap image. The background is a plain <img> (CSS
     * object-fit handles contain/cover), and doodle strokes are <path> elements in an <svg> layered
     * on top - each stroke is stored as its own list of points, so undo/redo/clear are just array
     * operations on `strokes`, not pixel manipulation.
     */
    interface DoodleCanvas {
        "clear": () => Promise<void>;
        /**
          * @default ['#1c1c1e', '#ff3b30', '#ff9500', '#ffcc00', '#34c759', '#0a84ff', '#af52de', '#ffffff']
         */
        "colors": string[];
        /**
          * Set to 'anonymous' when imageSrc is cross-origin and you need exportPng() to work - an un-annotated cross-origin image taints the canvas and toDataURL() throws.
         */
        "crossOrigin"?: 'anonymous' | 'use-credentials';
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Rasterizes the same markup exportSvg() would produce (background + strokes) at the stage's current on-screen size, and returns it as a PNG data URL.
         */
        "exportPng": (opts?: { includeBackground?: boolean; }) => Promise<string>;
        /**
          * Serializes the doodle layer - plus the background image as an <image> if one is set - into standalone, resolution-independent SVG markup.
         */
        "exportSvg": () => Promise<string>;
        /**
          * Mirrors CSS object-fit for how imageSrc is scaled into the stage.
          * @default 'contain'
         */
        "fit": 'contain' | 'cover';
        "getSnapshot": () => Promise<StrokeSnapshot>;
        /**
          * @default ''
         */
        "imageAlt": string;
        /**
          * URL of the base image to doodle over - works for both raster (png/jpg) and SVG sources, since both render fine in a plain <img>.
         */
        "imageSrc"?: string;
        /**
          * @default 28
         */
        "maxStrokeWidth": number;
        /**
          * @default 2
         */
        "minStrokeWidth": number;
        "redo": () => Promise<void>;
        /**
          * @default true
         */
        "showToolbar": boolean;
        /**
          * @default DEFAULT_COLORS[1]
         */
        "strokeColor": string;
        /**
          * @default 6
         */
        "strokeWidth": number;
        "undo": () => Promise<void>;
    }
}
export interface DoodleCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDoodleCanvasElement;
}
declare global {
    interface HTMLDoodleCanvasElementEventMap {
        "doodleChange": StrokeSnapshot;
    }
    /**
     * Freehand doodling overlay for an SVG or bitmap image. The background is a plain <img> (CSS
     * object-fit handles contain/cover), and doodle strokes are <path> elements in an <svg> layered
     * on top - each stroke is stored as its own list of points, so undo/redo/clear are just array
     * operations on `strokes`, not pixel manipulation.
     */
    interface HTMLDoodleCanvasElement extends Components.DoodleCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDoodleCanvasElementEventMap>(type: K, listener: (this: HTMLDoodleCanvasElement, ev: DoodleCanvasCustomEvent<HTMLDoodleCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDoodleCanvasElementEventMap>(type: K, listener: (this: HTMLDoodleCanvasElement, ev: DoodleCanvasCustomEvent<HTMLDoodleCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDoodleCanvasElement: {
        prototype: HTMLDoodleCanvasElement;
        new (): HTMLDoodleCanvasElement;
    };
    interface HTMLElementTagNameMap {
        "doodle-canvas": HTMLDoodleCanvasElement;
    }
}
declare namespace LocalJSX {
    /**
     * Freehand doodling overlay for an SVG or bitmap image. The background is a plain <img> (CSS
     * object-fit handles contain/cover), and doodle strokes are <path> elements in an <svg> layered
     * on top - each stroke is stored as its own list of points, so undo/redo/clear are just array
     * operations on `strokes`, not pixel manipulation.
     */
    interface DoodleCanvas {
        /**
          * @default ['#1c1c1e', '#ff3b30', '#ff9500', '#ffcc00', '#34c759', '#0a84ff', '#af52de', '#ffffff']
         */
        "colors"?: string[];
        /**
          * Set to 'anonymous' when imageSrc is cross-origin and you need exportPng() to work - an un-annotated cross-origin image taints the canvas and toDataURL() throws.
         */
        "crossOrigin"?: 'anonymous' | 'use-credentials';
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Mirrors CSS object-fit for how imageSrc is scaled into the stage.
          * @default 'contain'
         */
        "fit"?: 'contain' | 'cover';
        /**
          * @default ''
         */
        "imageAlt"?: string;
        /**
          * URL of the base image to doodle over - works for both raster (png/jpg) and SVG sources, since both render fine in a plain <img>.
         */
        "imageSrc"?: string;
        /**
          * @default 28
         */
        "maxStrokeWidth"?: number;
        /**
          * @default 2
         */
        "minStrokeWidth"?: number;
        /**
          * Fires after any mutation (stroke finished, clear, undo, redo) so a host can drive its own save/undo button state without polling getSnapshot().
         */
        "onDoodleChange"?: (event: DoodleCanvasCustomEvent<StrokeSnapshot>) => void;
        /**
          * @default true
         */
        "showToolbar"?: boolean;
        /**
          * @default DEFAULT_COLORS[1]
         */
        "strokeColor"?: string;
        /**
          * @default 6
         */
        "strokeWidth"?: number;
    }

    interface DoodleCanvasAttributes {
        "imageSrc": string;
        "imageAlt": string;
        "fit": 'contain' | 'cover';
        "crossOrigin": 'anonymous' | 'use-credentials';
        "strokeColor": string;
        "strokeWidth": number;
        "minStrokeWidth": number;
        "maxStrokeWidth": number;
        "showToolbar": boolean;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "doodle-canvas": Omit<DoodleCanvas, keyof DoodleCanvasAttributes> & { [K in keyof DoodleCanvas & keyof DoodleCanvasAttributes]?: DoodleCanvas[K] } & { [K in keyof DoodleCanvas & keyof DoodleCanvasAttributes as `attr:${K}`]?: DoodleCanvasAttributes[K] } & { [K in keyof DoodleCanvas & keyof DoodleCanvasAttributes as `prop:${K}`]?: DoodleCanvas[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Freehand doodling overlay for an SVG or bitmap image. The background is a plain <img> (CSS
             * object-fit handles contain/cover), and doodle strokes are <path> elements in an <svg> layered
             * on top - each stroke is stored as its own list of points, so undo/redo/clear are just array
             * operations on `strokes`, not pixel manipulation.
             */
            "doodle-canvas": LocalJSX.IntrinsicElements["doodle-canvas"] & JSXBase.HTMLAttributes<HTMLDoodleCanvasElement>;
        }
    }
}
