// directives/proxies.ts (the actual ThemeSelector/ThemeConfigurator component classes) and
// directives/index.ts (just a DIRECTIVES bulk-array convenience, not a re-export of the classes
// themselves) are generated by theme-ui's own Stencil build - see
// packages/theme-ui/stencil.config.ts's angularOutputTarget. Not hand-written, don't edit either.
// See ThemeUiService's own doc comment before pairing these with it in the same app.
export * from './directives/proxies';
export * from './directives';
export * from './theme-ui.service';
export type { ThemeConfigState, ThemePreset, ThemeCyclingOptions } from '@innotopic/theme-ui';
// Re-exported so consumers building a custom picker UI (e.g. LifeSuite's theme-config.component)
// or validating the curated list (e.g. LifeSuite's theme-contrast.spec.ts) don't need a second
// direct dependency on @innotopic/theme-ui just for these.
export {
  shadeColor,
  contrastRatio,
  colorDistance,
  MIN_UI_CONTRAST,
  MIN_COLOR_DISTANCE,
  curatedThemes,
  themePresets,
} from '@innotopic/theme-ui';
