[tool.poetry]
name = "shirt-gen-v2"
version = "0.1.0"
description = ""
authors = ["Jay Tailor <tailorj64@gmail.com>", "Karol Depka"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.112.0"}
langchain = "^0.2.12"
requests = "^2.32.3"
requests-oauthlib = "^2.0.0"
urllib3 = "^2.2.2"
langchain-openai = "^0.1.20"
langchain-community = "^0.2.11"
chromadb = "^0.5.5"
#qdrant-client = "^0.8.0"  # Add Qdrant client
python-dotenv = "^0.20.0"  # Add dotenv for environment variable management
pydantic = "^2.7.4"  # Add Pydantic for data validation
uvicorn = "^0.30.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
