[tool.poetry]
name = "shirt-gen-v2"
version = "0.1.0"
description = ""
authors = ["Jay Tailor <tailorj64@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.112.0"}
langchain = "^0.2.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
