/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Ports Angular's theme-config.component (the freeform "theme-configurator").
     */
    interface ThemeConfigurator {
    }
    /**
     * Ports Angular's theme-list.page (the preset grid / "theme-selector"). No longer talks to
     * NgRx - reads/writes
     * @innotopic /theme-ui's own store directly, which is now the single
     * source of truth (see the plan's "retire NgRx" decision).
     */
    interface ThemeSelector {
    }
}
declare global {
    /**
     * Ports Angular's theme-config.component (the freeform "theme-configurator").
     */
    interface HTMLThemeConfiguratorElement extends Components.ThemeConfigurator, HTMLStencilElement {
    }
    var HTMLThemeConfiguratorElement: {
        prototype: HTMLThemeConfiguratorElement;
        new (): HTMLThemeConfiguratorElement;
    };
    /**
     * Ports Angular's theme-list.page (the preset grid / "theme-selector"). No longer talks to
     * NgRx - reads/writes
     * @innotopic /theme-ui's own store directly, which is now the single
     * source of truth (see the plan's "retire NgRx" decision).
     */
    interface HTMLThemeSelectorElement extends Components.ThemeSelector, HTMLStencilElement {
    }
    var HTMLThemeSelectorElement: {
        prototype: HTMLThemeSelectorElement;
        new (): HTMLThemeSelectorElement;
    };
    interface HTMLElementTagNameMap {
        "theme-configurator": HTMLThemeConfiguratorElement;
        "theme-selector": HTMLThemeSelectorElement;
    }
}
declare namespace LocalJSX {
    /**
     * Ports Angular's theme-config.component (the freeform "theme-configurator").
     */
    interface ThemeConfigurator {
    }
    /**
     * Ports Angular's theme-list.page (the preset grid / "theme-selector"). No longer talks to
     * NgRx - reads/writes
     * @innotopic /theme-ui's own store directly, which is now the single
     * source of truth (see the plan's "retire NgRx" decision).
     */
    interface ThemeSelector {
    }
    interface IntrinsicElements {
        "theme-configurator": ThemeConfigurator;
        "theme-selector": ThemeSelector;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Ports Angular's theme-config.component (the freeform "theme-configurator").
             */
            "theme-configurator": LocalJSX.IntrinsicElements["theme-configurator"] & JSXBase.HTMLAttributes<HTMLThemeConfiguratorElement>;
            /**
             * Ports Angular's theme-list.page (the preset grid / "theme-selector"). No longer talks to
             * NgRx - reads/writes
             * @innotopic /theme-ui's own store directly, which is now the single
             * source of truth (see the plan's "retire NgRx" decision).
             */
            "theme-selector": LocalJSX.IntrinsicElements["theme-selector"] & JSXBase.HTMLAttributes<HTMLThemeSelectorElement>;
        }
    }
}
